name: Build

on:
  workflow_dispatch:

env:
  CADDY_VERSION: 2.7.6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      -
        name: Build arm-64
        run: docker buildx build \
             --platform linux/arm64 \
             --tag ${{ secrets.DOCKER_HUB_USER }}/caddy:${{ env.CADDY_VERSION }} \
             --tag ${{ secrets.DOCKER_HUB_USER }}/caddy:latest \
             --push \
             .
