name: Build

on:
  workflow_dispatch:

env:
  CADDY_VERSION: 2.7.6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      -
        name: Build arm64
        run: docker buildx create --use && docker buildx build github.com/itsprakashp/caddy --platform linux/arm64 --tag ${{ secrets.DOCKER_HUB_USER }}/caddy:${{ env.CADDY_VERSION }}-arm64 --tag ${{ secrets.DOCKER_HUB_USER }}/caddy:latest-arm64 --push
