name: Caddy Image Build

env:
  CADDY_VERSION: 2.7.6

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      -
        name: Create Buildx builder
        run: docker buildx create --use
      -
        name: Build Image and Push
        run: docker buildx build github.com/itsprakashp/caddy --platform linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6 --tag ${{ secrets.DOCKER_HUB_USER }}/caddy:${{ env.CADDY_VERSION }} --tag ${{ secrets.DOCKER_HUB_USER }}/caddy:latest --push
