name: build our image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout code
        uses: actions/checkout@v2
      - 
        name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - 
        name: build the image
        run: |
          docker buildx build \
            --push \
            --tag ${{ secrets.DOCKER_HUB_USER }}/caddy:latest \
            --platform linux/amd64,linux/arm64 .
